"""Agrega campo hora a GastoExtra

Revision ID: 8486c016de6a
Revises: 334a7380926e
Create Date: 2025-09-02 16:06:22.454418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8486c016de6a'
down_revision = '334a7380926e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_cliente')
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.alter_column('telefono',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('correo',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)

    with op.batch_alter_table('gasto_extra', schema=None) as batch_op:
        batch_op.add_column(sa.Column('hora', sa.Time(), nullable=False))
        batch_op.add_column(sa.Column('barbero_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('reporte_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'reporte_diario', ['reporte_id'], ['id'])
        batch_op.create_foreign_key(None, 'usuario', ['barbero_id'], ['id'])

    with op.batch_alter_table('pago_barbero', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_servicios', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('total_descuentos', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('reporte_id', sa.Integer(), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('porcentaje_ganancia',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.5)'))
        batch_op.alter_column('total_ganado',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('total_final',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.create_foreign_key(None, 'reporte_diario', ['reporte_id'], ['id'])
        batch_op.drop_column('descuento')

    with op.batch_alter_table('reserva', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('estado_pago',
               existing_type=sa.TEXT(),
               type_=sa.Enum('no_pagado', 'parcial', 'pagado', name='estado_pago_enum'),
               existing_nullable=False,
               existing_server_default=sa.text("'no_pagado'"))
        batch_op.alter_column('metodo_pago',
               existing_type=sa.TEXT(),
               type_=sa.Enum('yape', 'plin', 'efectivo', 'otro', name='metodo_pago_enum'),
               existing_nullable=True)

    with op.batch_alter_table('reserva_servicio', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('estado_servicio',
               existing_type=sa.TEXT(),
               type_=sa.Enum('en_espera', 'pendiente', 'en_proceso', 'terminado', 'cancelado', name='estado_servicio_enum'),
               existing_nullable=False,
               existing_server_default=sa.text("'pendiente'"))
        batch_op.alter_column('persona_atendida',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'reserva', ['reserva_id'], ['id'])

    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('dni',
               existing_type=sa.TEXT(),
               type_=sa.String(length=8),
               nullable=False)
        batch_op.alter_column('telefono',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('especialidad',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.alter_column('foto_url',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
        batch_op.create_unique_constraint(None, ['dni'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('foto_url',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('especialidad',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('telefono',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('dni',
               existing_type=sa.String(length=8),
               type_=sa.TEXT(),
               nullable=True)

    with op.batch_alter_table('reserva_servicio', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'reserva', ['reserva_id'], ['id'], ondelete='CASCADE')
        batch_op.alter_column('persona_atendida',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('estado_servicio',
               existing_type=sa.Enum('en_espera', 'pendiente', 'en_proceso', 'terminado', 'cancelado', name='estado_servicio_enum'),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'pendiente'"))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('reserva', schema=None) as batch_op:
        batch_op.alter_column('metodo_pago',
               existing_type=sa.Enum('yape', 'plin', 'efectivo', 'otro', name='metodo_pago_enum'),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('estado_pago',
               existing_type=sa.Enum('no_pagado', 'parcial', 'pagado', name='estado_pago_enum'),
               type_=sa.TEXT(),
               existing_nullable=False,
               existing_server_default=sa.text("'no_pagado'"))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('pago_barbero', schema=None) as batch_op:
        batch_op.add_column(sa.Column('descuento', sa.REAL(), server_default=sa.text('(0.0)'), nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('total_final',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('total_ganado',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('porcentaje_ganancia',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True,
               existing_server_default=sa.text('(0.5)'))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
        batch_op.drop_column('reporte_id')
        batch_op.drop_column('total_descuentos')
        batch_op.drop_column('total_servicios')

    with op.batch_alter_table('gasto_extra', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('reporte_id')
        batch_op.drop_column('barbero_id')
        batch_op.drop_column('hora')

    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.alter_column('correo',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('telefono',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)

    op.create_table('_alembic_tmp_cliente',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('dni', sa.VARCHAR(), nullable=True),
    sa.Column('nombre', sa.VARCHAR(), nullable=True),
    sa.Column('apellido', sa.VARCHAR(), nullable=True),
    sa.Column('documento_tipo', sa.VARCHAR(), nullable=True),
    sa.Column('observaciones', sa.TEXT(), nullable=True),
    sa.Column('telefono', sa.VARCHAR(), nullable=True),
    sa.Column('correo', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dni')
    )
    # ### end Alembic commands ###
